name: Publish Docker Back-end Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./back-end
          file: ./back-end/Dockerfile
          push: true
          tags: ghcr.io/danyelgranzotti/crud_user_nest_react_app/back-end:latest

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link & Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link 81ed9296-5129-4777-b9c6-a5dada9ba39d

          railway variables set DB_HOST=roundhouse.proxy.rlwy.net
          railway variables set DB_PORT=37833
          railway variables set DB_USERNAME=postgres
          railway variables set DB_PASSWORD=pnVNfBmxRzAwJjDMzShHjyqjrRAIHBcE
          railway variables set DB_DATABASE=railway

          railway up
